### ISSUE TITLE
Could not find ConEmu or ConEmu64 on path

### ISSUE THREAD

**Issue by fuddl** [connec/Open-in-ConEmu#1]
Got this message on using the shortcut:

```
Writing file /C/Users/fuddl/AppData/Roaming/Sublime Text 2/Packages/Open in ConEmu/Side Bar.sublime-menu with encoding UTF-8
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 337, in run_
  File ".\Open in ConEmu.py", line 20, in run
Exception: Could not find ConEmu or ConEmu64 on path
```

My ConEmu can be found at:

```
C:\Program Files (x86)\ConEmu\ConEmu.exe
```

what should I do in this case?

**Comment by connec** [comment]
It looks like you need to add `C:\Program Files (x86)\ConEmu` to your PATH.  Try running `where ConEmu` from a console, if it is not on your PATH it'll say something like "Could not find files for the given pattern(s)".

To add it to your PATH, see the answer to [this SO question](http://stackoverflow.com/questions/6318156/adding-python-path-on-windows-7) for a short series of steps (replacing `;C:\python27` with `;C:\Program Files (x86)\ConEmu`).

Let me know if that helps.

**Comment by fuddl** [comment]
works for me. Thanks :+1:
